---
"""
First: login to Docekr Hub 
Second: Checkout using checkout actions 
Third: Testing 
End: Link 
"""

name: checks 

on: [push] # every push changes  do...

jobs: 
  test-lint: 
    name: Test and lint 
    runs-on: ubuntu-20.04 # sys
    steps:
    # first step
      - name: Login to Docker Hub 
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USER}} # in github action repository 
          password: ${{secrets.DOCKERHUB_TOKEN}} # in github action repository 
    # second setep  
      - name: Checkout 
        uses: actions/checkout@v2
    # Next step
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
    #
      - name: Lint 
        run: docker-compose run --rm app sh -c "flake8"

